### ISSUE TITLE
Reputation not being applied

### ISSUE THREAD

**Issue by sharked76** [NodeBB/nodebb-rewards-essentials#16]
Hi, I have an existing forum, that I am now looking to enable reputation rewards.
I have enabled the plugin and created rules based on post count:

![image](https://user-images.githubusercontent.com/48071101/106935028-de1fbd80-66e8-11eb-9a1c-c00625e73961.png)

However after I enable the reward and click save, if I then go back to my user list and look, there is no change to reputations:

![image](https://user-images.githubusercontent.com/48071101/106935173-03143080-66e9-11eb-9ae6-e366d7d27d4e.png)

Even though those users are well over the threshold I set in the Rewards:
![image](https://user-images.githubusercontent.com/48071101/106935245-18895a80-66e9-11eb-8170-b133b3f60a8c.png)

Does it not apply the rewards for existing users? or is it only for new users?

**Comment by psychobunny** [comment]
hi @sharked76 the plugin doesn't retroactively apply rewards, but if any of those users post again they will receive the reward

**Comment by sharked76** [comment]
Once they post will it catch up for all that have been missed? Or the counter only starts from this point?

For example if Duane Cook makes a post his post count changes from 184 to 185 will he get the reward I have set for 25 posts and 50 posts as he has already past them?

**Comment by psychobunny** [comment]
hi @sharked76 internally the plugin works like this:

on some hook: "user posted"
check if condition is true: "user has more than 50 posts"
give reward

so the user in your example just needs to post once for the check(s) to pass. :)

**Comment by sharked76** [comment]
So if I understand, it is retroactive, its just not doing a scan and applying, its waiting until the user makes their next post?

If I have these setup:
![image](https://user-images.githubusercontent.com/48071101/106945905-66f12600-66f6-11eb-8961-57bf8cdb5cd7.png)


Once Duane Cook makes a new post, since he has more than 25 and also more than 50, he will have both of those rewards applied?

**Comment by psychobunny** [comment]
Ah I see your confusion from my original wording, sorry for that

The rewards are retroactive indeed but only checked once a new action is done for that user. So yes both rewards should be applied (assuming there's no bug :D)
