### ISSUE TITLE
Module is not showing in the widgets in Admin Control Panel

### ISSUE THREAD

**Issue by Neocron** [NodeBB/nodebb-rewards-essentials#2]
After installing fresh instance of the Nodebb forum and rewards system, the widget is not showing in the admin control panel

P.S. the module is installed in the node_modules/

**Comment by psychobunny** [comment]
I see, does everything else work though? The plugin should have been auto activated on a fresh install AFAIK

**Comment by Neocron** [comment]
Everything is ok everything have been installed but the plugin is not there.
We have restarted the forum several times still there is not plugin there.
The plugin is missing in the plugin list i can screenshot if you like.

**Comment by Neocron** [comment]
We had an old version of the nodebb, which the rewards system apparently was not working right. Everything is ok now

Thanks
