### ISSUE TITLE
No awards show if other award plugins are enabled.

### ISSUE THREAD

**Issue by yariplus** [NodeBB/nodebb-rewards-essentials#6]
I'm having weird issues if this plugin is enabled and other plugins add rewards. After you create the reward and go back to the page. The Awards are missing for all rewards, the select has a blank option in it. (Nothing is output to the log or browser console.)

![](http://puu.sh/ooEI4/78519c923d.png)

I created two new plugins that add new rewards, and they both work perfectly if both are enabled, as long this plugin isn't enabled.

I assume it's something with the templates, the amount of blank options in the award list is always equal to the amount of award inputs.

Checking ajaxify.data, and it does seem to have all the correct data in it.

**Comment by psychobunny** [comment]
Is the other two plugins available? I'll install and debug

**Comment by yariplus** [comment]
nope, I just added reward hooks to two other existing plugins. I couldn't find any other published rewards plugins. I'll make a repo for them so you can dl and test.

**Comment by yariplus** [comment]
https://github.com/yariplus/nbbrewardstest

Okay, the simplest possible plugins.

If I have rewards-essentials disabled and these plugins active, then I can create and save new rewards, then refresh the page, and everything is fine.

![](http://puu.sh/ooRgz/786caba556.png)

If I have rewards-essentials and these plugins active, then I can create and save new rewards, but once I refresh the page, the awards list is now gone.

![](http://puu.sh/ooRky/bf283cf809.png)

**Comment by psychobunny** [comment]
I managed to repro this (although how to fix it is another thing..)

I noticed that if rewards-essentials was always activated from the start prior to making any rewards, this works fine. It's only if you had rewards-essentials disabled first, then create a reward, and then re-enable it

**Comment by yariplus** [comment]
It doesn't matter for me if I have rewards-essentials enabled first.

Creating and saving rewards always works fine.

It's only when I go back to or refresh the page that the issue happens.

**Comment by wellenreiter01** [comment]
I have more or less the same issue after upgrading nodebb to v1.6.0
I did a manual upgrade and kept the existing rewards essentials module. No other changes in parallel.

Before the upgrade the module was working fine on nodebb 1.4.3
I have no other modules touching the rewards system

See also : https://community.nodebb.org/topic/11256/nodebb-rewards-essentials-after-upgrade-errorillegal-reward-no-inputs-found
