### ISSUE TITLE
 Edit New issue Awarding Users Reputation via Rewards Rules Doesn't Trigger Other Rewards Rules

### ISSUE THREAD

**Issue by deiden26** [NodeBB/nodebb-rewards-essentials#9]
NodeBB Version: 1.1.2
Git Hash: c0a4bf91f3241be113726ddea147bc2f4d1dc681
DB: Mongo
1. Create a rule that awards points (e.g. If User's Point Count Is > 0 Then Award Reputation Amount of reputation 1)
2. Create a rule that is triggered based on reputation (e.g. If User's Reputation Is >5 Add to Group Test Group 1)
3. Trigger rule created in step 1 until rule created in step to should trigger
4. Experience nothing happening
5. Up vote the user until the rule created in step 2 should trigger
6. Experience rule 2 triggering

**Comment by wellenreiter01** [comment]
you can see the triggers in the file .../nodebb-rewards-essentials/library.js.
The rule based on reputation is triggered by an upvote, so probably your Award reputation is not the same as an upvote.
I think you need to create a trigger here

**Comment by psychobunny** [comment]
Hi, reputation rewards have been fixed in the latest version of the plugin (0.0.10) and latest version of NodeBB (v1.7.x)
